"use client";
import "./globals.css";
import SideBar from "@/components/common/Sidebar";
import Header from "@/components/common/Header";
import { usePathname } from "next/navigation";

// export const metadata = {
//   title: "Toscatours",
//   description: "Generated by create next app",
// er

export default function RootLayout({ children }) {
  const pathName = usePathname();
  return (
    <html lang="en">
      <body>
        <div className="overflow-hidden w-full ">
          <div className="bg-mist-gray min-h-screen flex items-start">
            {pathName !== "/" && <SideBar />}
            <div className=" flex grow  flex-col w-12/12">
              {pathName !== "/" && <Header />}
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
